name: Fiefs
version: @version@
main: com.dansplugins.fiefs.Fiefs
api-version: 1.13
author: DanTheTechMan
depend: [MedievalFactions]
description: An expansion for Medieval Factions that allows faction members to create fiefs. Fiefs function as sub-factions, essentially.

commands:
  fiefs:
    description: The main command for Fiefs.
    usage: /fiefs
    aliases: [fi]

permissions:
  fiefs.help:
    default: true