name: Fiefs
version: v0.1
main: dansplugins.fiefs.Fiefs
api-version: 1.13
author: DanTheTechMan
depends: [MedievalFactions]

commands:
  fiefs:

permissions:
  fiefs.help:
    default: true
  fiefs.list:
    default: true
  fiefs.create:
    default: true
  fiefs.disband:
    default: true