name: Fiefs
version: 0.2
main: dansplugins.fiefs.Fiefs
api-version: 1.13
author: DanTheTechMan
depend: [MedievalFactions]

commands:
  fiefs:
  fi:

permissions:
  fiefs.help:
    default: true
  fiefs.list:
    default: true
  fiefs.create:
    default: true
  fiefs.disband:
    default: true
  fiefs.claim:
    default: true
  fiefs.unclaim:
    default: true
  fiefs.checkclaim:
    default: true
  fiefs.info:
    default: true