name: Fiefs
version: @version@
main: com.dansplugins.fiefs.Fiefs
api-version: 1.13
author: DanTheTechMan
depend: [MedievalFactions]

commands:
  fiefs:
    description: The main command for Fiefs.
    usage: /fiefs
    aliases: [fi]

permissions:
  fiefs.help:
    default: true