name: Fiefs
version: @version@
main: com.dansplugins.fiefs.Fiefs
api-version: 1.13
author: DanTheTechMan
depend: [MedievalFactions]
description: An expansion for Medieval Factions that allows faction members to create fiefs. Fiefs function as sub-factions, essentially.

commands:
  fiefs:
    description: The main command for Fiefs.
    aliases: [fi]

permissions:
  fiefs.help:
    default: true
    description: Allows the player to view the help menu.
  fiefs.create:
    default: true
    description: Allows the player to create a fief.
  fiefs.list:
    default: true
    description: Allows the player to view a list of all fiefs.